version: '3.8'

# Este archivo se usa automáticamente en desarrollo local
# Sobreescribe valores del docker-compose.yml principal

services:
  backend:
    env_file:
      - ./backend/.env.local
  frontend:
    env_file:
      - ./frontend/.env.local